# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 09:45
from __future__ import unicode_literals

import air_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirPorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_name', models.CharField(max_length=200)),
                ('plain_discribe', models.CharField(max_length=200)),
                ('current_aim', models.CharField(max_length=200, verbose_name=air_main.models.AirPorts)),
                ('time_left', models.IntegerField()),
            ],
        ),
    ]
