# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plain',
            name='current_aim',
            field=models.CharField(max_length=200, verbose_name='AirPorts'),
        ),
    ]
