# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_main', '0002_auto_20181009_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plain',
            name='current_aim',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='air_main.AirPorts'),
        ),
    ]
