# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_main', '0003_auto_20181009_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plain',
            name='plain_discribe',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
