# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_main', '0004_auto_20181009_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plain',
            name='time_left',
        ),
    ]
