# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_main', '0005_remove_plain_time_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plain',
            name='current_aim',
        ),
        migrations.AddField(
            model_name='plain',
            name='plain_port_in',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='air_main.AirPorts'),
        ),
        migrations.AddField(
            model_name='plain',
            name='plain_state',
            field=models.CharField(blank=True, choices=[('on the way', '\u0432 \u043f\u0443\u0442\u0438')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plain',
            name='plain_time_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plain',
            name='plain_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
