# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_main', '0006_auto_20181009_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='plain',
            name='plain_port_out',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plain_port_out', to='air_main.AirPorts'),
        ),
        migrations.AlterField(
            model_name='plain',
            name='plain_port_in',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plain_port_in', to='air_main.AirPorts'),
        ),
        migrations.AlterField(
            model_name='plain',
            name='plain_state',
            field=models.CharField(blank=True, choices=[('on the way', '\u0432 \u043f\u0443\u0442\u0438'), ('landed', '\u043f\u0440\u0438\u0437\u0435\u043c\u043b\u0438\u043b\u0441\u044f'), ('boarding ', '\u043f\u043e\u0441\u0430\u0434\u043a\u0430 \u043f\u0430\u0441\u0441\u0430\u0436\u0438\u0440\u043e\u0432'), ('disembarking', '\u0432\u044b\u0441\u0430\u0434\u043a\u0430 \u043f\u0430\u0441\u0441\u0430\u0436\u0438\u0440\u043e\u0432'), ('delay', '\u0437\u0430\u0434\u0435\u0440\u0436\u0430\u043d')], max_length=1, null=True),
        ),
    ]
