# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_main', '0007_auto_20181009_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_name', models.CharField(max_length=200)),
                ('plain_discribe', models.CharField(blank=True, max_length=200)),
                ('plain_type', models.CharField(blank=True, max_length=200)),
                ('plain_state', models.CharField(blank=True, choices=[('on the way', '\u0432 \u043f\u0443\u0442\u0438'), ('landed', '\u043f\u0440\u0438\u0437\u0435\u043c\u043b\u0438\u043b\u0441\u044f'), ('boarding ', '\u043f\u043e\u0441\u0430\u0434\u043a\u0430 \u043f\u0430\u0441\u0441\u0430\u0436\u0438\u0440\u043e\u0432'), ('disembarking', '\u0432\u044b\u0441\u0430\u0434\u043a\u0430 \u043f\u0430\u0441\u0441\u0430\u0436\u0438\u0440\u043e\u0432'), ('delay', '\u0437\u0430\u0434\u0435\u0440\u0436\u0430\u043d')], max_length=15, null=True)),
                ('plain_time_left', models.IntegerField(blank=True, null=True)),
                ('plain_port_in', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plain_port_in', to='air_main.AirPorts')),
                ('plain_port_out', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plain_port_out', to='air_main.AirPorts')),
            ],
        ),
        migrations.RemoveField(
            model_name='plain',
            name='plain_port_in',
        ),
        migrations.RemoveField(
            model_name='plain',
            name='plain_port_out',
        ),
        migrations.DeleteModel(
            name='Plain',
        ),
    ]
