# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_main', '0009_plains_plain_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='port_name_city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
